ch99/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name='blog'
urlpatterns=[
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>', views.TagObjectLV.as_view(), name='tagged_object_list'),

    path('search/', views.SearchFormView.as_view(), name='search'),

    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),


]

ch99/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

# from bookmark.views import BookmarkLV, BookmarkDV
# from bookmark.models import Bookmark
from mysite.views import HomeView

from django.conf.urls.static import static
from django.conf import settings

from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),
 
    #bookmark
    path('bookmark/',include('bookmark.urls')),

    #blog
    path('blog/', include('blog.urls')),

    #photo
    path('photo/', include('photo.urls')),

    #
    path('', HomeView.as_view(), name='home'),


    #인증관련
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),



]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ch99/photo/urls.py
from django.urls import path
from photo import views

app_name = 'photo'

urlpatterns=[
    path('',views.AlbumLV.as_view(), name='index'),
    # path('', ListView.as_view(model=Album), name='album_list' )
    path('album',views.AlbumLV.as_view(), name='album_list'),
    path('album/<int:pk>',views.AlbumDV.as_view(), name='album_detail'),
    path('photo/<int:pk>',views.PhotoDV.as_view(), name='photo_detail'),

    path('album/add/',views.AlbumphotoCV.as_view(), name='album_add'),
    path('album/change/',views.AlbumChangeLV.as_view(), name='album_change'),
    path('album/<int:pk>/update/',views.AlbumPhotoUV.as_view(), name='album_update'),
    path('album/<int:pk>/delete/',views.AlbumDelV.as_view(), name='album_delete'),
    
    path('photo/add/',views.PhotoCV.as_view(), name='photo_add'),
    path('photo/change/',views.PhotoChangeUV.as_view(), name='photo_change'),
    path('photo/<int:pk>/update/',views.PhotoUV.as_view(), name='photo_update'),
    path('photo/<int:pk>/delete/',views.PhotoDelV.as_view(), name='photo_delete'),

    

]

ch99/photo/models.py
from django.db import models
from django.urls import reverse
from photo.fields import ThumbnailImageField
# Create your models here.

class Album(models.Model):
    name=models.CharField(max_length=30)
    description = models.CharField('One Line Description',max_length=100, blank=True )
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True )

    class Meta:
        ordering=('name',)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))


class Photo(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    title = models.CharField('TITLE', max_length=30)
    description = models.TextField('Photo Description', blank=True)
    image = ThumbnailImageField(upload_to='photo/%Y?%m')
    upload_dt = models.DateTimeField('Upload Date', auto_now=True)
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True )


    class Meta:
        ordering=('title',)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))


class Publication(models.Model):
    title=models.CharField(max_length=30)
    albums = models.ManyToManyField(Album)



class Place(models.Model):
    name= models.CharField(max_length=50)
    address= models.CharField(max_length=80)

    def __str__(self):
        return f"Place-{self.name}"

class Restrunt(models.Model):
    place = models.OneToOneField(Place, on_delete=models.CASCADE)
    name= models.CharField(max_length=50)
    serves_pizza = models.BooleanField(default=False)

    def __str__(self):
        return f"Restrunt-{self.name}"

ch99/photo/forms.py
from django.forms import inlineformset_factory
from photo.models import Album, Photo

PhotoInlineFormSet = inlineformset_factory(Album, Photo,
    fields=['image','title','description'],
    extra = 2
)

ch99/photo/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import redirect
from mysite.views import OwnerOnlyMixin
from photo.forms import PhotoInlineFormSet
from photo.models import Album, Photo

class AlbumLV(ListView):
    model = Album

class AlbumDV(DetailView):
    model = Album

class PhotoDV(DetailView):
    model = Photo



class PhotoCV(LoginRequiredMixin, CreateView):
    model = Photo
    fields= ('album','title','image','description')
    success_url = reverse_lazy('photo:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class PhotoChangeUV(LoginRequiredMixin, ListView):
    model = Photo
    template_name = 'photo/photo_change_list.html'

    def get_queryset(self):
        return Photo.objects.filter(owner=self.request.user)


class PhotoUV(OwnerOnlyMixin, UpdateView):
    model = Photo
    fields= ('album','title','image','description')
    success_url = reverse_lazy('photo:index')

class PhotoDelV(OwnerOnlyMixin, DeleteView):
    model = Photo
    success_url = reverse_lazy('photo:index')




class AlbumphotoCV(LoginRequiredMixin, ListView):
    model = Album
    template_name = 'photo/album_change_list.html'

    def get_queryset(self):
        return Album.objects.filter(owner=self.request.user)

class AlbumDelV(OwnerOnlyMixin, DeleteView):
    model = Album
    success_url = reverse_lazy('photo:index')


class AlbumChangeLV(LoginRequiredMixin, CreateView):
    model = Album
    fields= ('name','description')
    success_url = reverse_lazy('photo:index')

    def get_context_data(self, **kwargs):
        #장고에 있는 디폴트 컨텍스트 변수 외에 추가적인 컨텍스트 변수를 정의하려고 하는 것
        context = super().get_context_data(**kwargs)(self)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FIELS)
        else:
            context['formset'] = PhotoInlineFormSet()
        return context

    def form_valid(self, form):
        form.isinstance.owner = self.request.user
        context = self.get_context_data
        formset = context['formset']

        for photoform in formset:
            photoform.isinstance.owner = self.request.user
        
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url)
        else:
            return self.render_to_response(self.get_context_data(form=form))
    

class AlbumPhotoUV(OwnerOnlyMixin, UpdateView):
    model = Album
    fields= ('name','description')
    success_url = reverse_lazy('photo:index')

    def get_context_data(self, **kwargs):
        #장고에 있는 디폴트 컨텍스트 변수 외에 추가적인 컨텍스트 변수를 정의하려고 하는 것
        context = super().get_context_data(**kwargs)(self)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FIELS, instance=self.object)
        else:
            context['formset'] = PhotoInlineFormSet(instance=self.object)
        return context
    
    def form_valid(self, form):
        context = self.get_context_data
        formset = context['formset']
        
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url)
        else:
            return self.render_to_response(self.get_context_data(form=form))

ch99/photo/templates/photo/album_change_list.html
{% extends 'base.html' %}
 

{% block title %}album_change_list.html{% endblock %}

{% block content %}
<h4>album change -{{user}}</h4>
<p class='font-italic'>this is a create or update</p>

<table class='table table-bordered table-condensed table-striped'>
    <Thead>
        <tr class='table-primary'>
            <th>Name</th>
            <th>description</th>
            <th>owner</th>
            <th>update</th>
            <th>Delete</th>
        </tr>
    </Thead>
    <tbody>
        {% for item in object_list %}  
        <tr>
          <td>{{item.name}}</td>
          <td>{{item.description}}</td>
          <td>{{item.owner}}</td>
          <td><a href="{% url 'photo:photo_update' item.id %}">update</a></td>
          <td><a href="{% url 'photo:photo_delete' item.id %}">delete</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

ch99/photo/templates/photo/album_confirm_delete.html
{% extends 'base.html' %}


{% block title %}album_confirm_delete.html{% endblock %}

{% block content %}
<h4>album delete</h4>

<form action='.' method='post'>
    {% csrf_token %}
    <p>{{object}} 지울거?</p>
    <input type='submit' value='confirm' />
</form>

{% endblock %}

ch99/photo/templates/photo/album_detail.html
{% exends 'base.html' %}

{% block title %}album_detail.html{% endblock %}


{% block extra-style %}
<style>
    thumbnail{
    border:5px soid #ccc;
}
</style>
{% endblock %}



{% block content %}
    <div class='mt-5'>
        <span class='h2'>{{object.name}}&emsp;</span>
        <span class='h5 font-detail'>{{object.decription}}</span>
    </div>

    <hr style="margin: 0 0 20px 0 ">

    <div class='row'>
        {%  for photo in object.photo_set.all %} 
        <div class='thumbnail'>
            <a href = "{{photo.get_absolute_url}}">
                <img src="{{photo.image.thumb_url}}" style="width:100%">
            </a>
        </div>
        <ul>
            <li class ='font-italic'>{{photo.title}}</li>
            <li class ='font-italic'>{{photo.upload_dt|date="Y-m-d"}}</li>
        </ul>
    
        {% endfor %}
    </div>


{% endblock %}

ch99/photo/templates/photo/album_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}  

{% block title %}album_form.html{% endblock %}

{% block content %}
<h4>album create/update -{{user}}</h4>
<p class='font-italic'>this is a create or update</p>

{%if form.errors %}
<div class='alert alert-danger'>
    <div class='font-weight-bold'>Wrong! Please correct the errors below</div>
    {{form.errors}}
</div>
{% endif %}


{%if formset.errors %}
<div class='alert alert-danger'>
    <div class='font-weight-bold'>Wrong! Please correct the errors below</div>
    {{formerrors}}
</div>
{% endif %}

{% if form.is_multipart %}
<!-- 폼이나 폼셋 체크해서 multipart인코딩 필요한지 여부 알려줌
true면 enctpye=multipart/form-data로 지정 -->
<form enctype="multipart/form-data" action='' method='post'>
{% else %}
<form action='' method='post'></form>
{% endif %}
    {% csrf_token %}  
    <div class='form-group row'>
        {{ form.name|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold"}}
        <div class='col-sm-5'>
            {{form.name|add_class:'form-control'|attr:'autofocus'}}
        </div>
    </div>
    <div class='form-group row'>
        {{form.description|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold'}}
        <div class='col-sm-5'>
            {{form.description|add_class:'form-control'}}
        </div>
    </div>

    {{formset.management_form}}
    <!-- 폼셋에 있는 각 폼을 다룰 경우 이 변수 반드시 추가 필요
    장고의 템플릿엔진이 폼셋에 들어있는 폼의 개수 등을 알 수 있어야 하기 때문 -->
    {% for form in formset %} 
        {{form.id}}
        {# form.album #}
        <div class='form-group row'>
            {{form.image|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold'}}
            <div class='col-sm-5'>
                {{form.image|add_class:'form-control'}}
            </div>
        </div>
        <div class='form-group row'>
            {{form.title|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold'}}
            <div class='col-sm-5'>
                {{form.title|add_class:'form-control'}}
            </div>
        </div>
        <div class='form-group row'>
            {{form.description|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold'}}
            <div class='col-sm-5'>
                {{form.description|add_class:'form-control'}}
            </div>
        </div>
        

    {% endfor %}
    
   

    <div class='form-group'>
        <div class='offset-sm-2 col-sm-5'>
            <input type='submit' value='register' class='btn btn-info'>
        </div>
    </div>
</form>


{% endblock %}

ch99/photo/templates/photo/album_list.html
{% extends 'base.html' %}

{% block title %}album_list.html{% endblock %}

{% block extra-style %}
<style>
    thumbnail{
    border:3px soid #ccc;
}
</style>
{% endblock %}

{% block content %}
    {%  for item in object_list %}  
    <div class = 'mt-5'>
        <a class='h2' href="{% url 'photo:album_detail' item.id %}">
        {{item.name}}
        </a>&emsp;
        <span class ='font-italic h5'>{{item.description}}</span>
    </div>

    <hr style='margin: 0 0 20px 0;'>
    
    <div class='row'>
        {%  for photo in itme.photo_set.all|slice:":5" %}
        <div class='ml-5'>
            <div class='thumbnail'>
                <a href="{{photo.get_absolute_url}}">
                    <img src="{{photo.image.thumb_url}}" style="width:100%">
                </a>
            </div>
        </div>  
        {% endfor %}
    </div>
    {% endfor %}
{% endblock %}

ch99/photo/templates/photo/photo_change_list.html
{% extends 'base.html' %}
 

{% block title %}photo_change_list.html{% endblock %}

{% block content %}
<h4>Photo change -{{user}}</h4>
<p class='font-italic'>this is a create or update</p>

{%if form.errors %}
<div class='alert alert-danger'>
    <div class='font-weight-bold'>Wrong! Please correct the errors below</div>
    {{form.errors}}
</div>
{% endif %}

<table class='table table-bordered table-condensed table-striped'>
    <Thead>
        <tr class='table-primary'>
            <th>Album</th>
            <th>title</th>
            <th>description</th>
            <th>owner</th>
            <th>update</th>
            <th>Delete</th>
        </tr>
    </Thead>
    <tbody>
        {% for item in object_list %}  
        <tr>
          <td>{{item.album}}</td>
          <td>{{item.title}}</td>
          <td>{{item.description}}</td>
          <td>{{item.owner}}</td>
          <td><a href="{% url 'photo:photo_update' item.id %}">update</a></td>
          <td><a href="{% url 'photo:photo_delete' item.id %}">delete</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

ch99/photo/templates/photo/photo_confirm_delete.html
{% extends 'base.html' %}


{% block title %}photo_confirm_delete.html{% endblock %}

{% block content %}
<h4>photo delete</h4>

<form action='.' method='post'>
    {% csrf_token %}
    <p>{{object}} 지울거?</p>
    <input type='submit' value='confirm' />
</form>

{% endblock %}

ch99/photo/templates/photo/photo_detail.html
{% exends 'base.html' %}

{% block title %}photo_detail.html{% endblock %}

{% block content %}
<h2 class='mt-5'>{{object.title}}</h2>
<div class='row'>
    <div class='col-md-9'>
        <a href="{{object.image.url}}">
            <img src="{{object.image.url}}"  style="width:100%">
        </a>
    </div>
    <ul class='col-md-3 mt-3'>
        <li class='h5'>Photo description</li>
        {% if object.decription %}<p>{{object.decription|linebreaks}}</p>
        {% else %}<p>(blank)</p>
        {% endif %}

        <li class='h5'>Date Uploaded</li>
            <p class='font-italic'>{{object.upload_dt}}</p>
        
        <li class='h5'>Album Name</li>
            <p class='font-italic'>
                <a href = "{% url 'photo:album_detail' object.album.id %}">
                    {{object.album.name}}
                </a>
            </p>
    </ul>
</div>
{% endblock %}

ch99/photo/templates/photo/photo_forms.html
{% extends 'base.html' %}
{% load widget_tweaks %}  

{% block title %}photo_form.html{% endblock %}

{% block content %}
<h4>photo create/update -{{user}}</h4>
<p class='font-italic'>this is a create or update</p>

{%if form.errors %}
<div class='alert alert-danger'>
    <div class='font-weight-bold'>Wrong! Please correct the errors below</div>
    {{form.errors}}
</div>
{% endif %}

{% if form.is_multipart %}
<!-- 폼이나 폼셋 체크해서 multipart인코딩 필요한지 여부 알려줌
true면 enctpye=multipart/form-data로 지정 -->
<form enctype="multipart/form-data" action='' method='post'>
{% else %}
<form action='' method='post'></form>
{% endif %}
    {% csrf_token %}  
    <div class='form-group row'>
        {{ form.album|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold"}}
        <div class='col-sm-5'>
            {{form.album|add_class:'form-control'|attr:'autofocus'}}
        </div>
    </div>
    <div class='form-group row'>
        {{form.url|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold'}}
        <div class='col-sm-5'>
            {{form.url|add_class:'form-control'}}
        </div>
        <div class='col-sm-5 my-auto'>
            <a href="{% url 'photo:album_add' %}">Add album</a>
        </div>
    </div>
    <div class='form-group row'>
        {{ form.album|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold"}}
        <div class='col-sm-5'>
            {{form.album|add_class:'form-control'|attr:'autofocus'}}
        </div>
    </div>
    <div class='form-group row'>
        {{form.title|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold'}}
        <div class='col-sm-5'>
            {{form.title|add_class:'form-control'}}
        </div>
    </div>
    <div class='form-group row'>
        {{form.image|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold'}}
        <div class='col-sm-5'>
            {{form.image|add_class:'form-control'}}
        </div>
    </div>
    <div class='form-group row'>
        {{form.description|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold'}}
        <div class='col-sm-5'>
            {{form.description|add_class:'form-control'}}
        </div>
    </div>
   

    <div class='form-group'>
        <div class='offset-sm-2 col-sm-5'>
            <input type='submit' value='register' class='btn btn-info'>
        </div>
    </div>
</form>


{% endblock %}