ch99/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name='blog'
urlpatterns=[
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>', views.TagObjectLV.as_view(), name='tagged_object_list'),

    path('search/', views.SearchFormView.as_view(), name='search'),

    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),


]

ch99/bookmark/urls.py
from django.urls import path, re_path
from bookmark.views import *
from bookmark.models import Bookmark
app_name='bookmark'

urlpatterns=[
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(), name='detail'),
    path('add/', BookmarkCreateView.as_view(), name='add'),
    path('change/', BookmarkChangeView.as_view(), name='change'),
    path('<int:pk>/update/', BookmarkUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', BookmarkDeleteView.as_view(), name='delete'),

]

ch99/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

# from bookmark.views import BookmarkLV, BookmarkDV
# from bookmark.models import Bookmark
from mysite.views import HomeView

from django.conf.urls.static import static
from django.conf import settings

from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),
 
    #bookmark
    path('bookmark/',include('bookmark.urls')),

    #blog
    path('blog/', include('blog.urls')),

    #photo
    path('photo/', include('photo.urls')),

    #
    path('', HomeView.as_view(), name='home'),


    #인증관련
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),



]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ch99/bookmark/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Bookmark(models.Model):
    title = models.CharField('TITLE', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)


    def __str__(self):
        return self.title

ch99/bookmark/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
#로그인 데코레이터 기능 클래스에 적용시 사용
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin
#소유저만 콘텐츠 수정 가능하도록 하는 클래스 
from bookmark.models import Bookmark


# Create your views here.
class BookmarkLV(ListView):
    model = Bookmark
    #디폴트 컨텍스트변수 object_list
    #모델명 (소문자)_list.html


class BookmarkDV(DetailView):
    model = Bookmark
    #디폴트 컨텍스트변수 object
    #모델명 (소문자)_list.html


class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields=['title','url']
    success_url = reverse_lazy('bookmark:index')

    def form_valid(self,form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class BookmarkChangeView(LoginRequiredMixin, ListView):
    template_name='bookmark/bookmark_change_list.html'

    def get_queryset(self):
        #화면에 출력할 레코드 리스트 반환
        return Bookmark.objects.filter(owner=self.request.user)


class BookmarkUpdateView(OwnerOnlyMixin, UpdateView):
    model = Bookmark
    fields=['title','url']
    success_url = reverse_lazy('bookmark:index')


class BookmarkDeleteView(OwnerOnlyMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

ch99/bookmark/templates/bookmark/bookmark_change_list.html
{% extends 'base.html' %}
 

{% block title %}bookmark_change_list.html{% endblock %}

{% block content %}
<h4>Bookmark change -{{user}}</h4>
<p class='font-italic'>this is a create or update</p>

{%if form.errors %}
<div class='alert alert-danger'>
    <div class='font-weight-bold'>Wrong! Please correct the errors below</div>
    {{form.errors}}
</div>
{% endif %}

<table class='table table-bordered table-condensed table-striped'>
    <Thead>
        <tr class='table-primary'>
            <th>Title</th>
            <th>Url</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    </Thead>
    <tbody>
        {% for item in object_list %}  
        <tr>
          <td>{{item.title}}</td>
          <td>{{item.url}}</td>
          <td>{{item.owner}}</td>
          <td><a href="{% url 'bookmark:update' item.id %}">update</a></td>
          <td><a href="{% url 'bookmark:delete' item.id %}">delete</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

ch99/bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}


{% block title %}bookmark_confirm_delete.html{% endblock %}

{% block content %}
<h4>Bookmark delete</h4>

<form action='.' method='post'>
    {% csrf_token %}
    <p>{{object}} 지울거?</p>
    <input type='submit' value='confirm' />
</form>

{% endblock %}

ch99/bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}bookmark_detail.html{% endblock %}



{% block content %}
    <h4>{{ object.title }}</h4>
    <br>

    <ul>
        <li>URL: <a href="{{object.url}}">{{object.url}}</a></li>
    </ul>

{% endblock %}













<!-- <!DOCTYPE html>
<html>
    <head>
        <title>Django Bookmark Detail</title>
    </head>
    <body>
        <div id='content'>
            <h1>{{object.title}}</h1>
            <ul>
                <li>URL: <a href="{{object.url}}">{{object.url}}</a></li>
            </ul>
        </div>
    </body>
</html> -->

ch99/bookmark/templates/bookmark/bookmark_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}  

{% block title %}bookmark_form.html{% endblock %}

{% block content %}
<h4>Bookmark create/update -{{user}}</h4>
<p class='font-italic'>this is a create or update</p>

{%if form.errors %}
<div class='alert alert-danger'>
    <div class='font-weight-bold'>Wrong! Please correct the errors below</div>
    {{form.errors}}
</div>
{% endif %}

<form action='.' method='post' class='card pt-3'>
    {% csrf_token %}  
    <div class='form-group row'>
        {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold"}}
        <div class='col-sm-5'>
            {{form.title|add_class:'form-control'|attr:'autofocus'}}
        </div>
    </div>
    <div class='form-group row'>
        {{form.url|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold'}}
        <div class='col-sm-5'>
            {{form.url|add_class:'form-control'}}
        </div>
    </div>
   

    <div class='form-group'>
        <div class='offset-sm-2 col-sm-5'>
            <input type='submit' value='register' class='btn btn-info'>
        </div>
    </div>
</form>


{% endblock %}

ch99/bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}bookmark_list.html{% endblock %}



{% block content %}
    <h4>Bookmark list</h4>
    <br>

    <ul>
        {% for bookmark in object_list %}
            <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{bookmark}}</a></li>
        {% endfor %} 
    </ul>

{% endblock %}





<!-- <!DOCTYPE html>
<html>
    <head>
        <title>Django Bookmark List</title>
    </head>
    <body>
        <div id='content'>
            <h1>Bookmark List</h1>
            <ul>
                {% for bookmark in object_list %}
                    <li><a href="{% url 'detail' bookmark.id %}">{{bookmark}}</a></li>
                {% endfor %}
            </ul>
        </div>
    </body>
</html> -->