ch99/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name='blog'
urlpatterns=[
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>', views.TagObjectLV.as_view(), name='tagged_object_list'),

    path('search/', views.SearchFormView.as_view(), name='search'),

    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),


]

ch99/bookmark/urls.py
from django.urls import path, re_path
from bookmark.views import *
from bookmark.models import Bookmark
app_name='bookmark'

urlpatterns=[
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(), name='detail'),
    path('add/', BookmarkCreateView.as_view(), name='add'),
    path('change/', BookmarkChangeView.as_view(), name='change'),
    path('<int:pk>/update/', BookmarkUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', BookmarkDeleteView.as_view(), name='delete'),

]

ch99/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

# from bookmark.views import BookmarkLV, BookmarkDV
# from bookmark.models import Bookmark
from mysite.views import HomeView

from django.conf.urls.static import static
from django.conf import settings

from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),
 
    #bookmark
    path('bookmark/',include('bookmark.urls')),

    #blog
    path('blog/', include('blog.urls')),

    #photo
    path('photo/', include('photo.urls')),

    #
    path('', HomeView.as_view(), name='home'),


    #인증관련
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),



]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ch99/photo/urls.py
from django.urls import path
from photo import views

app_name = 'photo'

urlpatterns=[
    path('',views.AlbumLV.as_view(), name='index'),
    # path('', ListView.as_view(model=Album), name='album_list' )
    path('album',views.AlbumLV.as_view(), name='album_list'),
    path('album/<int:pk>',views.AlbumDV.as_view(), name='album_detail'),
    path('photo/<int:pk>',views.PhotoDV.as_view(), name='photo_detail'),

    path('album/add/',views.AlbumphotoCV.as_view(), name='album_add'),
    path('album/change/',views.AlbumChangeLV.as_view(), name='album_change'),
    path('album/<int:pk>/update/',views.AlbumPhotoUV.as_view(), name='album_update'),
    path('album/<int:pk>/delete/',views.AlbumDelV.as_view(), name='album_delete'),
    
    path('photo/add/',views.PhotoCV.as_view(), name='photo_add'),
    path('photo/change/',views.PhotoChangeUV.as_view(), name='photo_change'),
    path('photo/<int:pk>/update/',views.PhotoUV.as_view(), name='photo_update'),
    path('photo/<int:pk>/delete/',views.PhotoDelV.as_view(), name='photo_delete'),

    

]

ch99/mysite/views.py
from django.views.generic.base import TemplateView
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import AccessMixin
#뷰 처리 진입단계에서 적절한 권한을 갖추었는지 판별할때 사용하는 믹스인 클래스

class HomeView(TemplateView):
    template_name = 'home.html'

class UserCreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')

class UserCreateDoneTV(TemplateView):
    template_name = 'registration/register_done.html'

class OwnerOnlyMixin(AccessMixin):
    #로그인한 사용자가 콘텐츠 소유자인지 판별
    raise_exception = True
    #소유자가 아닌경우 True)>403처리>우리가 할 거
    #False면 로그인페이지로 리다이렉트
    permission_denied_message = 'owner on;y update/delete the object'
    #403시, 보여줄 메세지

def dispatch(self,request, *args, **kwargs):
    #get이전에 dispatch메소드오버라이딩
    #accessMixin 쓰는 경우엔 dispatch메소드오버라이딩 하는게 일반적
    obj = self.get_object()
    if request.user != obj.owner:
        return self.handle_no_permission()
    return super().dispatch(request, *args, **kwargs)

ch99/mysite/templates/base.html
<!DOCTYPE html>
<html lang='ko'>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-UA-Compatible" content= "IE=edge">
        <meta name='viewport' content = "width=device-width, initial-scale=1">
        
    
        <title>{% block title %}Django Web Programming{% endblock %}</title>
        <!-- <link rel='stylesheet' href=''> -->
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        {% block extra-style %}{% endblock %}
    </head>
   

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <span class="navbar-brand" href="#">Navbar</span>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>


                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item mx-1 btn btn-pimary">
                            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                        </li>
                        <li class="nav-item mx-1 btn btn-pimary">
                            <a class="nav-link" href="{% url 'bookmark:index' %}">Bookmark</a>
                        </li>
                        <li class="nav-item mx-1 btn btn-pimary">
                            <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
                        </li>
                        <li class="nav-item mx-1 btn btn-pimary">
                            <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
                        </li>
                        <li class="nav-item mx-1 btn btn-pimary">
                            <a class="nav-link" href="{% url 'photo:index' %}">Photo</a>
                        </li>
                        <li class="nav-item mx-1 btn btn-pimary">
                            <a class="nav-link"href="{% url 'blog:search' %}">Search</a>
                        </li>
                        <li class="nav-item dropdown mx-1 btn btn-pimary">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                            Dropdown
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a></li>
                                <li><a class="dropdown-item" href="{% url 'blog:post_archive' %}">blog</a></li>
                                <li><a class="dropdown-item" href="{% url 'blog:search' %}">Search</a></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled">Disabled</a>
                        </li>
                    </ul>
                    <form class="d-flex" action="" method="post">
                        {% csrf_token %}
                        <input class="form-control me-2" type="search" placeholder="global_Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                    <ul class='navbar-nav ml-5 mr-5'>
                        <li class='nav-item dropdown mx-1 btn btn-ptimary'>
                            {% if user.is_active %} 
                                <a class='nav-link dropdown-toggle text-black' href='#' data-toggle='dropdown'>
                                    <i class='fas fa-user'></i>&ensp;{% firstof user.get_shor_name user.get_username %}&ensp;
                                </a>
                                <div class='dropdown-menu'>
                                    <a class='dropdown-item' href="{% url 'logout' %}">LOGOUT</a>
                                    <a class='dropdown-item' href="{% url 'password_change' %}">Change_password</a>
                                </div>
                            {% else %}
                                <a class='nav-link dropdown-toggle text-black' href='#' data-toggle="dropdown">
                                    <i class='fas fa-user'></i>&ensp;Anonymous&ensp;
                                </a>
                                <div class='dropdown-menu'>
                                    <a class='dropdown-item' href="{% url 'login' %}">LOGIN</a>
                                    <a class='dropdown-item' href="{% url 'register' %}">Register</a>
                                </div>
                            {% endif %}
                        </li>

                    </ul>
                </div>
            </div>
            
        </nav>
        {% block content %}
        {% endblock %}
        {% block footer %}{% endblock %}
        <!-- <fotter class='fixed-bottom bg-info'>
            <h4>This is FOOTER area</h4>
        </fotter> -->

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>        
        <script src="https//kit.fontwesome.com/c998a172fe.js"></script>
        {% block extra-script %}{% endblock %}
    </body>
</html>

ch99/mysite/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}home.html{% endblock %}

{% block extra-style %}
<!-- <style type="text/css">
    .home_image
</style> -->
{% endblock %}



{% block content %}
    <h4>This is COnTEnT area</h4>
{% endblock %}

{% block footer %}
<fotter class='fixed-bottom bg-info'>
    <h4>This is FOOTER area</h4>
</fotter>
{% endblock %}