ch99/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name='blog'
urlpatterns=[
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>', views.TagObjectLV.as_view(), name='tagged_object_list'),

    path('search/', views.SearchFormView.as_view(), name='search'),

    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),


]

ch99/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

# from bookmark.views import BookmarkLV, BookmarkDV
# from bookmark.models import Bookmark
from mysite.views import HomeView

from django.conf.urls.static import static
from django.conf import settings

from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),
 
    #bookmark
    path('bookmark/',include('bookmark.urls')),

    #blog
    path('blog/', include('blog.urls')),

    #photo
    path('photo/', include('photo.urls')),

    #
    path('', HomeView.as_view(), name='home'),


    #인증관련
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),



]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ch99/blog/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from django.utils.text import slugify

class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
    content = models.TextField('CONTENT')
    tags = TaggableManager()
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIY DATE', auto_now=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_posts'
        ordering=('-modify_dt',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous(self):
        return self.get_previous_by_modify_dt()

    def get_next(self):
        return self.get_next_by_modify_dt()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)

ch99/blog/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

ch99/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView, FormView
from blog.forms import PostSearchForm
from django.db.models import Q
from django.shortcuts import render
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView
from blog.models import Post
from django.conf import settings
# Create your views here.

from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin


class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name='posts'
    paginate_by=2

class PostDV(DetailView):
    model=Post

    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        context['disqus_short'] = f"{settings.DISQUS_SHORTNAME}"
        context['disqus_id'] = f"post={self.object.id}-{self.object.slug}"
        context['disqus_url'] = f"{settings.DISQUS_MY_DOMAIN}{self.object.get_absolute_url()}"
        context['disqus_title'] = f"{self.object.slug}"
        return context


class PostAV(ArchiveIndexView):
    model=Post
    template_name = 'blog/post_archive.html' 
    date_field = 'modify_dt' 
    

class PostYAV(YearArchiveView):
    model=Post
    date_field = 'modify_dt'
    make_object_list = True


class PostMAV(MonthArchiveView):
    model=Post
    date_field = 'modify_dt'

class PostDAV(DayArchiveView):
    model=Post
    date_field = 'modify_dt'

class PostTAV(TodayArchiveView):
    model=Post
    date_field = 'modify_dt'

class TagCloudTV(TemplateView):
    template_name = 'taggit/taggit_cloud.hmtl'

class TagObjectLV(ListView):
    template_name = 'taggit/taggit_post_list.html'
    model=Post

    def get_queryset(self):
        return Post.objects.filter(tags__name = self.kwargs.get('tag'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.kwargs['tag']
        return context


class SearchFormView(FormView):
    #FormView는 Get일때 폼을 화면에 보여주고, 입력기다림
    #데이터 입력>제출 시, Post로 접수> 데이터 유효성 검사>form_valid()실행후>리다이렉트
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form):
        #유효성 검사 실시해 에러없음 form_valid실행
        #유효성 검사 통과하면 입력 데이터들은 cleaned_data 사전에 존재 
        searchWord = form.cleaned_data['search_word']
        #Q = filter조건 다양하게 가능
        #__incontains : 대소문자 구별x , 단어 포함되있는지
        #distinct: 중복 객체 제외
        post_list = Post.objects.filter(Q(title__icontains=searchWord) | 
            Q(description__icontains=searchWord) |  Q(content__icontains=searchWord)).distinct()

        context = {}
        context['form'] = form
        context['search_form'] = searchWord
        context['object_list'] = post_list

        #form_valid는 보통 HttpResponseRedirect객체 반환
        #지금건 재정의한거
        return render(self.request, self.template_name, context)


class PostCreateView(LoginRequiredMixin, CreateView):
    model=Post
    fields=['title','slug', 'description', 'content','tags']
    initial={'slug': 'auto-filling-do-not-input'}
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class PostChangeLV(LoginRequiredMixin, ListView):
    template_name = 'blog/post_change_list.html'

    def get_queryset(self):
        return Post.objects.filter(owner=self.request.user)

class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields=['title','slug', 'description', 'content','tags']
    success_url = reverse_lazy('blog:index')

class PostDeleteView(OwnerOnlyMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')

ch99/blog/templates/blog/post_all.html
{% extends 'base.html' %}
{% load static %}

{% block title %}post_all.html{% endblock %}



{% block content %}
    <h4>{{ object.title }}</h4>
    <br>

    <ul>
        <li>URL: <a href="{{object.url}}">{{object.url}}</a></li>
    </ul>


    <h1>Blosg List</h1>
    <br>

    {% for post in posts %}
        <h3><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h3>
        {{ post.moedify_dt|date:"N d, Y" }}
        <p>{{ post.decription }}</p>
    {%  endfor %}

    <br>

    <div>
        <span>
            {% if page_obj.has_previous %} 
                <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
            {% endif %}

            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number}}">NEXTPage</a>
            {% endif %}
        
        </span>
    </div>
{% endblock %}

ch99/blog/templates/blog/post_archive.html
<!-- now태그 - 현재 날짜, 시간 원하는 포멧으로 출력 -->
<h1>Post Archive until {% now "N d, Y" %}</h1>
<ul>
    {% for date in date_list %}
    <!-- date_list컨텍스트 변수: DateQuerySet객체 리스트 담은거: 
                            QuerySet 객체리스트에서 날짜 정보만 추출해 담고 있는거 -->

        <li style='display : inline'>
            <a href = "{% url 'blog:post_year_archive' date|date:'Y' %}">
                Year - {{date|date:'Y'}} 
            </a> 
        </li> 
    {% endfor %}
</ul>
<br/>

<div>
    <ul>
        {% for post in object_list %}
            <li>
                {{ post.modify_dt|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
                <a href ="{{ post.get_abolute_url}}"><strong>{{post.title}}</strong></a>
            </li>
        {% endfor %}
    </ul>
</div>

ch99/blog/templates/blog/post_archive_day.html
<h1>Post Archive for {{ day|date:"N d, Y"}}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>
            {{ post.modify_dt|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
            <a href ="{{ post.get_abolute_url}}"><strong>{{post.title}}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>

ch99/blog/templates/blog/post_archive_month.html
<h1>Post Archive for {{ month|date:"N, Y"}}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>
            {{ post.modify_dt|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
            <a href ="{{ post.get_abolute_url}}"><strong>{{post.title}}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>

ch99/blog/templates/blog/post_archive_year.html
<h1>Post Archive for {{ year|date:"Y"}}</h1>

<ul>
    {% for date in date_list %}
    <li style='display : inline'>
        <a href = "{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">
            {{date|date:'F'}} 
        </a>
    </li> 
    {% endfor %}
</ul>

<br>

<div>
    <ul>
        {% for post in object_list %}
        <li>
            {{ post.modify_dt|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
            <a href ="{{ post.get_abolute_url}}"><strong>{{post.title}}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>

ch99/blog/templates/blog/post_change_list.html
{% extends 'base.html' %}
 

{% block title %}post_change.html{% endblock %}

{% block content %}
<h4>post change -{{user}}</h4>
<p class='font-italic'>this is a change</p>



<table class='table table-bordered table-condensed table-striped'>
    <Thead>
        <tr class='table-primary'>
            <th>Title</th>
            <th>description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    </Thead>
    <tbody>
        {% for item in object_list %}  
        <tr>
          <td>{{item.title}}</td>
          <td>{{item.description}}</td>
          <td>{{item.owner}}</td>
          <td><a href="{% url 'blog:update' item.id %}">update</a></td>
          <td><a href="{% url 'blog:delete' item.id %}">delete</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

ch99/blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}


{% block title %}blog_confirm_delete.html{% endblock %}

{% block content %}
<h4>blog delete</h4>

<form action='.' method='post'>
    {% csrf_token %}
    <p>{{object}} 지울거?</p>
    <input type='submit' value='confirm' />
</form>

{% endblock %}

ch99/blog/templates/blog/post_detail.html
<h1>{{object.title}}</h1>
<br>

<p>
    {% if object.get_previous %}
    <a href = "{{ object.get_previous.get_absolute_url}}" title="View previous post">
        &laquo;- {{object.get_previous}}
    </a>
    {% endif %}

    {% if object.get_next %}
    | <a href = "{{object.get_next.get_absolute_url}}" title="View next post">
        {{object.get_next}}  -&laquo;
    </a>
    {% endif %}

</p>

<p>{{object.modify_dt|date:"j F Y"}}</p>
<br>
<div>
    {{object.content|linebreaks}}
</div>

<br>
<div>
    <b>TAGS</b> <i class='fas fa-tag'></i>
    <!-- 패키지에 정의된 커스텀 태그 사용위해 모듈 로딩 -->
    {% load taggit_templatetags2_tags %}
    <!-- 커스텀 태그 사용해 object객체에 달려있는 태크들의 리스트를 추출함-->
    <!-- object:뷰에서 넘겨주는 컨텍스트 변수,Post객체 담김 -->
    {% get_tags_for_object object as 'tags' %} 
    {% for tag in tags %}  
        <a href="{% url 'blog:tagged_object_list' tag.name %}">{{tag.name}}</a>
    {% endfor %}  
    &emsp;
    <a href="{% url 'blog:tag_cloud' %}"><span class='btn btn-info btn-sm'>TagCloud</span></a>
    <br>
    <div id='disqus_thread'></div>

    {% block extra-script %}
    <script>
        var disqus_config = function(){
            this.page.identifier = '{{disqus_id}}'
            this.page.url = '{{disqus_url}}'
            this.page.title = '{{disqus_title}}'

        };

        (function(){
            var d = document, s = d.createElement('script');
            s.src = 'https://{{disqus_short}}.disqus.com/embed.js';
            s.setAttribute('data-timestamp', +new Date());
            (d.head || d.body).appendChild(s);
        })();
    </script>
    
    {% endblock %}
</div>

ch99/blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}  

{% block title %}post_form.html{% endblock %}

{% block content %}
<!-- <h4>Bookmark create/update -{{user}}</h4> -->
<p class='font-italic'>this is blog post form</p>

{%if form.errors %}
<div class='alert alert-danger'>
    <div class='font-weight-bold'>Wrong! Please correct the errors below</div>
    {{form.errors}}
</div>
{% endif %}

<form action='.' method='post' class='card pt-3'>
    {% csrf_token %}  
    <div class='form-group row'>
        {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold"}}
        <div class='col-sm-5'>
            {{form.title|add_class:'form-control'|attr:'autofocus'}}
        </div>
    </div>
    <div class='form-group row'>
        {{ form.slug|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold"}}
        <div class='col-sm-5'>
            {{form.slug|add_class:'form-control'|attr:'autofocus'}}
        </div>
    </div>
    <div class='form-group row'>
        {{form.description|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold'}}
        <div class='col-sm-5'>
            {{form.description|add_class:'form-control'}}
        </div>
    </div>
    <div class='form-group row'>
        {{form.content|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold'}}
        <div class='col-sm-5'>
            {{form.content|add_class:'form-control'}}
        </div>
    </div>
    <div class='form-group row'>
        {{form.tags|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold'}}
        <div class='col-sm-5'>
            {{form.tags|add_class:'form-control'}}
        </div>
    </div>
   

    <div class='form-group'>
        <div class='offset-sm-2 col-sm-5'>
            <input type='submit' value='register' class='btn btn-info'>
        </div>
    </div>
</form>


{% endblock %}

ch99/blog/templates/blog/post_search.html
{% extends 'base.html' %} 

{% block title %}post_search.html{% endblock%}

{% block content %}
<h1>Blog Search</h1>
<br>

<form action='.' method='post'>
    {% csrf_token %}
    {{form.as_table}}
    <input type='submit' value = 'submit' class='btn btn-pimary btn-sm'>
</form>

{% if object_list %}
{% for post in object_list %} 
<h2><a href="{{ post.get_abolute_url}}">{{post.title}}</a></h2>
{{ post.modify_date|date:"N d, Y"}} 
<p>{{post.description}}</p>
{% endfor %}

{% elif search_term %} 
<b>Search Word {{ search_term}} Not Found</b>
{% endif %}

{% endblock%}